title = "demo-api-test gitleaks config"
redact = true
fail = true

[allowlist]
paths = ["data/payloads","data/schemas","tests/","^\\.env\\.example$"]
regexes = [
	"^(dummy|example|sample)_?key$",
	# Allow example placeholders for API key in docs and examples
	"API_KEY=(replace-with-your-api-key|your_key_if_required)"
]

[[rules]]
id = "api-key-variable"
description = "Matches API_KEY style hardcoded tokens"
regex = '''(?i)(?:const|let|var)?\s*api[_-]?key\s*[:=]\s*["']?[0-9A-Za-z-_]{8,64}["']?'''
secretGroup = 0
entropy = 0.0
